version: "4.16.3"

services:

  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db



  db:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_USER: postgrest
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql


